"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { api } from "./api";
import ScreeningWorkspace from "./screening-workspace";

type Operation = { operation_id: string; status: string; stage: string; error: string | null; provider_runs: { provider: string; status: string; retrieved: number }[] };
type Project = { id: string; title: string; status: string; ideas: { raw_text: string }[]; literature_count: number; plan_status: string | null; operation: Operation | null };
type Plan = { id: string; version: number; status: string; content: { provisional_title: string; problem_statement: string; research_objective: string; candidate_research_questions: string[]; recommended_research_question: string; recommended_review_method: string; recommended_framework: string; scope: string; key_concepts: string[]; assumptions: string[]; uncertainties: string[]; rationale: string } };
type Framework = { structured_elements: { framework_type: string; elements: { name: string; values: string[] }[]; missing_elements: string[]; rationale: string; confidence: number } };
type Strategy = { content: { concepts: { label: string; terms: string[] }[]; provider_queries: { provider: string; query_text: string; rationale: string }[]; filters: { year_from?: number; year_to?: number }; rationale: string; known_limitations: string[] } };
type Literature = { id: string; title: string; authors: string[]; publication_year: number | null; doi: string | null; venue: string | null; discovered_via: string[]; verification_status: string; duplicate_status: string };

const tokenKey = "ranahresearch-token";

export default function Home() {
  const [token, setToken] = useState(() => typeof window === "undefined" ? "" : localStorage.getItem(tokenKey) ?? ""); const [idea, setIdea] = useState(""); const [project, setProject] = useState<Project | null>(null);
  const [plan, setPlan] = useState<Plan | null>(null); const [framework, setFramework] = useState<Framework | null>(null); const [strategy, setStrategy] = useState<Strategy | null>(null); const [literature, setLiterature] = useState<Literature[]>([]); const [busy, setBusy] = useState(""); const [error, setError] = useState("");
  const [year, setYear] = useState(""); const [verification, setVerification] = useState(""); const [provider, setProvider] = useState("");
  const [projects, setProjects] = useState<Project[]>([]);
  const [offset, setOffset] = useState(0);
  const projectId = project?.id;
  const [workspace, setWorkspace] = useState("discovery");
  const saveToken = (value: string) => { setToken(value); localStorage.setItem(tokenKey, value); };
  const refresh = useCallback(async (projectId: string) => {
    const filters = new URLSearchParams({ offset: String(offset) }); if (year) filters.set("year", year); if (verification) filters.set("verification_status", verification); if (provider) filters.set("provider", provider); const suffix = `?${filters}`;
    const [nextProject, nextPlan, nextFramework, nextStrategy, nextLiterature] = await Promise.all([api<Project>(`/projects/${projectId}`, {}, token), api<Plan | null>(`/projects/${projectId}/plan`, {}, token), api<Framework | null>(`/projects/${projectId}/framework`, {}, token), api<Strategy | null>(`/projects/${projectId}/search-strategy`, {}, token), api<Literature[]>(`/projects/${projectId}/literature${suffix}`, {}, token)]);
    setProject(nextProject); setPlan(nextPlan); setFramework(nextFramework); setStrategy(nextStrategy); setLiterature(nextLiterature); return nextProject;
  }, [provider, token, verification, year, offset]);
  useEffect(() => { if (!token) return; let active = true; api<Project[]>("/projects", {}, token).then(rows => { if (active) setProjects(rows); }).catch(caught => { if (active) setError(String(caught)); }); return () => { active = false; }; }, [token, projectId]);
  useEffect(() => { if (!projectId) return; let active = true; const timer = setTimeout(() => { if (active) void refresh(projectId).catch(caught => setError(String(caught))); }, 150); return () => { active = false; clearTimeout(timer); }; }, [projectId, refresh]);
  useEffect(() => { if (!project?.operation || !["PENDING", "RUNNING"].includes(project.operation.status)) return; let active = true; const timer = window.setInterval(async () => { try { const operation = await api<Operation>(`/projects/${project.id}/operations/${project.operation!.operation_id}`, {}, token); if (active) { await refresh(project.id); if (operation.error) setError(operation.error); } } catch (caught) { if (active) setError(caught instanceof Error ? caught.message : "Could not refresh operation"); } }, 1500); return () => { active = false; window.clearInterval(timer); }; }, [project, refresh, token]);
  const run = async (label: string, path: string, body?: object) => { if (!project) return; setBusy(label); setError(""); try { await api<Operation>(`/projects/${project.id}${path}`, { method: "POST", body: JSON.stringify(body ?? {}) }, token); await refresh(project.id); } catch (caught) { setError(caught instanceof Error ? caught.message : "The operation failed"); } finally { setBusy(""); } };
  const create = async (event: FormEvent) => { event.preventDefault(); if (!idea.trim() || !token) return; setBusy("create"); setError(""); try { const created = await api<Project>("/projects", { method: "POST", body: JSON.stringify({ idea }) }, token); setProject(created); setIdea(""); await refresh(created.id); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not create project"); } finally { setBusy(""); } };
  const waiting = project?.operation && ["PENDING", "RUNNING"].includes(project.operation.status); const statusText = project?.operation ? `${project.operation.stage} · ${project.operation.status}` : "No operation running"; const planReady = plan?.status === "PROPOSED" || plan?.status === "APPROVED"; const frameworkElements = useMemo(() => framework?.structured_elements.elements ?? [], [framework]);

  return <main className="shell">
    <header className="topbar"><div><p className="kicker">RANAHRESEARCH / DISCOVERY</p><h1>Research, with a visible trail.</h1></div><span className="state">{project ? project.status : "READY"}</span></header>
    <section className="intro"><p>Review your discovery corpus, approve a protocol, and screen titles and abstracts with an auditable decision history.</p></section>
    <nav className="filters" aria-label="Project navigation"><label>Open project<select value={project?.id ?? ""} onChange={event => { setOffset(0); setYear(""); setVerification(""); setProvider(""); setError(""); setWorkspace("discovery"); if (!event.target.value) { setProject(null); return; } void refresh(event.target.value).catch(caught => setError(String(caught))); }}><option value="">New project</option>{projects.map(row => <option key={row.id} value={row.id}>{row.title}</option>)}</select></label></nav>
    {!project ? <section className="start-panel"><div><p className="eyebrow">Start a project</p><h2>What are you curious about?</h2><p className="muted">Your original idea stays attached to the project as the first research artifact.</p></div><form onSubmit={create}><label htmlFor="token">Local API token</label><input id="token" value={token} onChange={(event) => saveToken(event.target.value)} placeholder="Paste token from .env.discovery" required /><label htmlFor="idea">Research idea</label><textarea id="idea" value={idea} onChange={(event) => setIdea(event.target.value)} placeholder="Pengaruh generative AI terhadap hasil belajar mahasiswa di pendidikan tinggi." rows={5} required /><button disabled={busy === "create"}>{busy === "create" ? "Creating project…" : "Create project"}</button>{error && <div className="notice error" role="alert">{error}</div>}</form></section> : <>
      <section className="project-heading"><div><p className="eyebrow">Project</p><h2>{project.title}</h2><p className="muted">{project.ideas.at(-1)?.raw_text}</p></div><div className="metric"><strong>{project.literature_count}</strong><span>discovered records</span></div></section>
      {error && <div className="notice error" role="alert">{error}</div>}
      <nav className="actions" aria-label="Research workspace"><button aria-pressed={workspace === "discovery"} onClick={() => setWorkspace("discovery")}>Discovery</button><button aria-pressed={workspace === "screening"} onClick={() => setWorkspace("screening")}>Protocol & screening</button></nav>
      {workspace === "screening" ? <ScreeningWorkspace key={project.id} projectId={project.id} token={token} /> : <>
      <section className="progress-strip"><span className={`pulse ${waiting ? "live" : ""}`} aria-hidden="true" /><strong>{statusText}</strong>{project.operation?.error && <span className="muted">{project.operation.error}</span>}<span className="progress-providers">{project.operation?.provider_runs.map((run) => `${run.provider}: ${run.status}`).join(" · ")}</span></section>
      <div className="workspace-grid">
        <section className="panel plan-panel"><div className="panel-head"><div><p className="eyebrow">01 / Research plan</p><h2>{plan ? plan.content.provisional_title : "A provisional direction"}</h2></div>{plan && <span className="tag">{plan.status}</span>}</div>{!plan ? <Empty text="Generate a plan from the saved idea." action="Generate plan" onClick={() => run("plan", "/plan/generate")} disabled={!!waiting} /> : <><dl className="facts"><div><dt>Objective</dt><dd>{plan.content.research_objective}</dd></div><div><dt>Question</dt><dd>{plan.content.recommended_research_question}</dd></div><div><dt>Method / framework</dt><dd>{plan.content.recommended_review_method} · {plan.content.recommended_framework}</dd></div><div><dt>Scope</dt><dd>{plan.content.scope}</dd></div></dl><p className="rationale">{plan.content.rationale}</p>{planReady && plan.status === "PROPOSED" && <button onClick={() => run("approve", "/plan/approve", { plan_id: plan.id })} disabled={!!waiting}>{busy === "approve" ? "Approving…" : "Approve plan"}</button>}</>}</section>
        <section className="panel framework-panel"><div className="panel-head"><div><p className="eyebrow">02 / Framework</p><h2>{framework?.structured_elements.framework_type ?? "Question structure"}</h2></div></div>{!framework ? <Empty text="The framework is selected with the plan." /> : <><div className="elements">{frameworkElements.map((element) => <div className="element" key={element.name}><span>{element.name}</span><p>{element.values.join("; ")}</p></div>)}</div><p className="rationale">{framework.structured_elements.rationale}</p></>}</section>
        <section className="panel strategy-panel"><div className="panel-head"><div><p className="eyebrow">03 / Search strategy</p><h2>Provider queries</h2></div>{strategy && <span className="tag">READY</span>}</div>{!strategy ? <Empty text={plan?.status === "APPROVED" ? "Create broad discovery queries." : "Approve the plan before building queries."} action={plan?.status === "APPROVED" ? "Generate strategy" : undefined} onClick={plan?.status === "APPROVED" ? () => run("strategy", "/search-strategy/generate") : undefined} disabled={!!waiting} /> : <><div className="concepts">{strategy.content.concepts.map((concept) => <div key={concept.label}><strong>{concept.label}</strong><span>{concept.terms.join(" · ")}</span></div>)}</div><div className="queries">{strategy.content.provider_queries.map((query) => <div key={query.provider}><span>{query.provider}</span><code>{query.query_text}</code></div>)}</div><p className="rationale">{strategy.content.known_limitations.join(" ")}</p><button onClick={() => run("search", "/literature/search")} disabled={!!waiting}>{busy === "search" ? "Starting…" : "Start literature discovery"}</button></>}</section>
      </div>
      <section className="panel literature-panel"><div className="panel-head"><div><p className="eyebrow">04 / Discovery corpus</p><h2>Canonical literature records</h2></div><span className="tag">{literature.length} shown</span></div><div className="filters"><label htmlFor="year-filter">Year<input id="year-filter" inputMode="numeric" value={year} onChange={(event) => setYear(event.target.value)} placeholder="Any" /></label><label htmlFor="verification-filter">Identity<select id="verification-filter" value={verification} onChange={(event) => setVerification(event.target.value)}><option value="">Any status</option><option value="VERIFIED">Verified</option><option value="PARTIALLY_VERIFIED">Partial</option><option value="CONFLICT">Conflict</option><option value="UNVERIFIED">Unverified</option></select></label><label htmlFor="provider-filter">Provider<select id="provider-filter" value={provider} onChange={(event) => setProvider(event.target.value)}><option value="">Any provider</option><option value="crossref">Crossref</option><option value="openalex">OpenAlex</option><option value="semantic_scholar">Semantic Scholar</option></select></label></div>{literature.length === 0 ? <Empty text={waiting ? "Results will appear as providers finish." : "No records yet. Start discovery after approving the plan and strategy."} /> : <div className="table-wrap"><table><thead><tr><th>Title</th><th>Year</th><th>DOI</th><th>Via</th><th>Identity</th><th>Duplicate</th></tr></thead><tbody>{literature.map((work) => <tr key={work.id}><td><strong>{work.title}</strong><small>{work.authors.join(", ") || "Author metadata pending"}</small></td><td>{work.publication_year ?? "—"}</td><td>{work.doi ?? "—"}</td><td>{work.discovered_via.join(", ") || "—"}</td><td><span className="status-text">{work.verification_status}</span></td><td>{work.duplicate_status}</td></tr>)}</tbody></table></div>}</section>
      <div className="actions"><button disabled={offset === 0} onClick={() => setOffset(Math.max(0, offset - 100))}>Previous literature page</button><span>Page {Math.floor(offset / 100) + 1}</span><button disabled={literature.length < 100} onClick={() => setOffset(offset + 100)}>Next literature page</button></div>
      </>}
    </>}
    <footer>Discovery records are not screened studies. Every plan, query, provider run, normalization, deduplication, and verification outcome remains auditable.</footer>
  </main>;
}

function Empty({ text, action, onClick, disabled }: { text: string; action?: string; onClick?: () => void; disabled?: boolean }) { return <div className="empty"><p>{text}</p>{action && <button onClick={onClick} disabled={disabled}>{action}</button>}</div>; }
