"""evidence_extraction_and_validation

Revision ID: 5baf40062978
Revises: 7b834e827c1d
Create Date: 2026-09-20 20:46:50.245156

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from alembic import op

revision: str = '5baf40062978'
down_revision: str | None = '7b834e827c1d'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extraction_schemas',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('protocol_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'APPROVED', 'SUPERSEDED', name='extractionschemastatus', native_enum=False, length=40), nullable=False),
    sa.Column('schema_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by_agent_run_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_agent_run_id'], ['agent_runs.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['protocol_id'], ['review_protocols.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'version')
    )
    op.create_index(op.f('ix_extraction_schemas_project_id'), 'extraction_schemas', ['project_id'], unique=False)
    op.create_index(op.f('ix_extraction_schemas_protocol_id'), 'extraction_schemas', ['protocol_id'], unique=False)
    op.create_table('evidence',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('study_id', sa.Uuid(), nullable=False),
    sa.Column('work_id', sa.Uuid(), nullable=True),
    sa.Column('extraction_schema_id', sa.Uuid(), nullable=True),
    sa.Column('evidence_type', sa.String(length=30), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('value_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('value_type', sa.Enum('REPORTED', 'DERIVED', 'USER_ENTERED', 'MISSING', name='evidencevaluetype', native_enum=False, length=40), nullable=False),
    sa.Column('derivation', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('verification_status', sa.Enum('UNVERIFIED', 'VERIFIED', 'PARTIAL', 'CONFLICT', name='evidenceverificationstatus', native_enum=False, length=40), nullable=False),
    sa.Column('status', sa.Enum('CURRENT', 'SUPERSEDED', name='evidencestatus', native_enum=False, length=40), nullable=False),
    sa.Column('superseded_by', sa.Uuid(), nullable=True),
    sa.Column('extractor_run_id', sa.Uuid(), nullable=True),
    sa.Column('entered_by', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entered_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['extraction_schema_id'], ['extraction_schemas.id'], ),
    sa.ForeignKeyConstraint(['extractor_run_id'], ['agent_runs.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['superseded_by'], ['evidence.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['work_id'], ['work_records.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('evidence_current', 'evidence', ['project_id', 'status'], unique=False)
    op.create_index('evidence_study_field', 'evidence', ['study_id', 'field_name'], unique=False)
    op.create_index(op.f('ix_evidence_project_id'), 'evidence', ['project_id'], unique=False)
    op.create_index(op.f('ix_evidence_study_id'), 'evidence', ['study_id'], unique=False)
    op.create_table('evidence_provenance',
    sa.Column('evidence_id', sa.Uuid(), nullable=False),
    sa.Column('parsed_document_id', sa.Uuid(), nullable=True),
    sa.Column('chunk_id', sa.Uuid(), nullable=True),
    sa.Column('work_id', sa.Uuid(), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('section', sa.String(length=500), nullable=True),
    sa.Column('quote_start', sa.Integer(), nullable=True),
    sa.Column('quote_end', sa.Integer(), nullable=True),
    sa.Column('evidence_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parsed_document_id'], ['parsed_documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['work_id'], ['work_records.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_provenance_evidence_id'), 'evidence_provenance', ['evidence_id'], unique=False)
    op.create_table('evidence_verifications',
    sa.Column('evidence_id', sa.Uuid(), nullable=False),
    sa.Column('verification_method', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('UNVERIFIED', 'VERIFIED', 'PARTIAL', 'CONFLICT', name='evidenceverificationstatus', native_enum=False, length=40), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('findings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reviewer_id', sa.Uuid(), nullable=True),
    sa.Column('agent_run_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_verifications_evidence_id'), 'evidence_verifications', ['evidence_id'], unique=False)
    op.create_table('study_characteristics',
    sa.Column('study_id', sa.Uuid(), nullable=False),
    sa.Column('dimension', sa.String(length=50), nullable=False),
    sa.Column('value_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evidence_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('study_id', 'dimension')
    )
    op.create_index(op.f('ix_study_characteristics_study_id'), 'study_characteristics', ['study_id'], unique=False)
    # ### end Alembic commands ###
    op.execute("""
    CREATE FUNCTION protect_evidence_history() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN RAISE EXCEPTION 'Evidence verification history is immutable'; END $$;
    CREATE TRIGGER evidence_verification_immutable
    BEFORE UPDATE OR DELETE ON evidence_verifications
    FOR EACH ROW EXECUTE FUNCTION protect_evidence_history();
    CREATE TRIGGER evidence_provenance_immutable
    BEFORE UPDATE OR DELETE ON evidence_provenance
    FOR EACH ROW EXECUTE FUNCTION protect_evidence_history();
    CREATE FUNCTION protect_evidence_values() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      IF TG_OP = 'DELETE' THEN RAISE EXCEPTION 'Evidence is superseded, never deleted'; END IF;
      IF (to_jsonb(NEW) - ARRAY['status','superseded_by','verification_status','updated_at'])
         IS DISTINCT FROM
         (to_jsonb(OLD) - ARRAY['status','superseded_by','verification_status','updated_at']) THEN
        RAISE EXCEPTION 'Correct evidence by superseding it, not by editing the value';
      END IF;
      RETURN NEW;
    END $$;
    CREATE TRIGGER evidence_superseded_not_edited BEFORE UPDATE OR DELETE ON evidence
    FOR EACH ROW EXECUTE FUNCTION protect_evidence_values();
    ALTER TABLE evidence ADD CHECK (confidence IS NULL OR confidence BETWEEN 0 AND 1);
    ALTER TABLE evidence ADD CHECK (value_type != 'DERIVED' OR derivation IS NOT NULL);
    ALTER TABLE evidence ADD CHECK (value_type != 'MISSING' OR value_json IS NULL);
    ALTER TABLE evidence_verifications ADD CHECK (confidence IS NULL OR confidence BETWEEN 0 AND 1);
    """)


def downgrade() -> None:
    op.execute("DROP TRIGGER evidence_superseded_not_edited ON evidence")
    op.execute("DROP FUNCTION protect_evidence_values()")
    op.execute("DROP TRIGGER evidence_provenance_immutable ON evidence_provenance")
    op.execute("DROP TRIGGER evidence_verification_immutable ON evidence_verifications")
    op.execute("DROP FUNCTION protect_evidence_history()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_study_characteristics_study_id'), table_name='study_characteristics')
    op.drop_table('study_characteristics')
    op.drop_index(op.f('ix_evidence_verifications_evidence_id'), table_name='evidence_verifications')
    op.drop_table('evidence_verifications')
    op.drop_index(op.f('ix_evidence_provenance_evidence_id'), table_name='evidence_provenance')
    op.drop_table('evidence_provenance')
    op.drop_index(op.f('ix_evidence_study_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_project_id'), table_name='evidence')
    op.drop_index('evidence_study_field', table_name='evidence')
    op.drop_index('evidence_current', table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_extraction_schemas_protocol_id'), table_name='extraction_schemas')
    op.drop_index(op.f('ix_extraction_schemas_project_id'), table_name='extraction_schemas')
    op.drop_table('extraction_schemas')
    # ### end Alembic commands ###
