"""studies_and_study_linking

Revision ID: 7b834e827c1d
Revises: d34a95117685
Create Date: 2026-09-20 20:27:51.851300

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from alembic import op

revision: str = '7b834e827c1d'
down_revision: str | None = 'd34a95117685'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('studies',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('study_label', sa.String(length=50), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('study_type', sa.Enum('RCT', 'QUASI_EXPERIMENTAL', 'COHORT', 'CASE_CONTROL', 'CROSS_SECTIONAL', 'QUALITATIVE', 'MIXED_METHODS', 'SYSTEMATIC_REVIEW', 'OTHER', name='studytype', native_enum=False, length=40), nullable=False),
    sa.Column('status', sa.Enum('CANDIDATE', 'CONFIRMED', 'NEEDS_REVIEW', name='studystatus', native_enum=False, length=40), nullable=False),
    sa.Column('country', sa.String(length=200), nullable=True),
    sa.Column('setting', sa.String(length=300), nullable=True),
    sa.Column('recruitment_period', sa.String(length=200), nullable=True),
    sa.Column('registration_id', sa.String(length=100), nullable=True),
    sa.Column('superseded_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['superseded_by'], ['studies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'study_label')
    )
    op.create_index(op.f('ix_studies_project_id'), 'studies', ['project_id'], unique=False)
    op.create_index(op.f('ix_studies_registration_id'), 'studies', ['registration_id'], unique=False)
    op.create_table('study_link_decisions',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('work_id', sa.Uuid(), nullable=False),
    sa.Column('candidate_work_id', sa.Uuid(), nullable=True),
    sa.Column('study_id', sa.Uuid(), nullable=True),
    sa.Column('decision', sa.Enum('LINK', 'KEEP_SEPARATE', 'UNCERTAIN', name='studylinkdecisiontype', native_enum=False, length=40), nullable=False),
    sa.Column('relationship_type', sa.Enum('PRIMARY_REPORT', 'SECONDARY_REPORT', 'CONFERENCE_ABSTRACT', 'FOLLOW_UP', 'PROTOCOL', 'CORRECTION', 'OTHER', name='studyworkrelationship', native_enum=False, length=40), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('signals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('decided_by', sa.String(length=10), nullable=False),
    sa.Column('reviewer_id', sa.Uuid(), nullable=True),
    sa.Column('agent_run_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ),
    sa.ForeignKeyConstraint(['candidate_work_id'], ['work_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_id'], ['work_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_link_decisions_project_id'), 'study_link_decisions', ['project_id'], unique=False)
    op.create_index(op.f('ix_study_link_decisions_work_id'), 'study_link_decisions', ['work_id'], unique=False)
    op.create_table('study_works',
    sa.Column('study_id', sa.Uuid(), nullable=False),
    sa.Column('work_id', sa.Uuid(), nullable=False),
    sa.Column('relationship_type', sa.Enum('PRIMARY_REPORT', 'SECONDARY_REPORT', 'CONFERENCE_ABSTRACT', 'FOLLOW_UP', 'PROTOCOL', 'CORRECTION', 'OTHER', name='studyworkrelationship', native_enum=False, length=40), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('linked_by', sa.String(length=100), nullable=False),
    sa.Column('agent_run_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_id'], ['work_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('study_id', 'work_id')
    )
    op.create_index(op.f('ix_study_works_study_id'), 'study_works', ['study_id'], unique=False)
    op.create_index(op.f('ix_study_works_work_id'), 'study_works', ['work_id'], unique=False)
    # ### end Alembic commands ###
    op.execute("""
    CREATE FUNCTION protect_study_link_history() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN RAISE EXCEPTION 'Study link decisions are immutable'; END $$;
    CREATE TRIGGER study_link_decision_immutable BEFORE UPDATE OR DELETE ON study_link_decisions
    FOR EACH ROW EXECUTE FUNCTION protect_study_link_history();
    ALTER TABLE study_works ADD CHECK (confidence IS NULL OR confidence BETWEEN 0 AND 1);
    ALTER TABLE study_link_decisions ADD CHECK (confidence IS NULL OR confidence BETWEEN 0 AND 1);
    ALTER TABLE study_link_decisions ADD CHECK (decided_by IN ('AI','HUMAN','SYSTEM'));
    """)


def downgrade() -> None:
    op.execute("DROP TRIGGER study_link_decision_immutable ON study_link_decisions")
    op.execute("DROP FUNCTION protect_study_link_history()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_study_works_work_id'), table_name='study_works')
    op.drop_index(op.f('ix_study_works_study_id'), table_name='study_works')
    op.drop_table('study_works')
    op.drop_index(op.f('ix_study_link_decisions_work_id'), table_name='study_link_decisions')
    op.drop_index(op.f('ix_study_link_decisions_project_id'), table_name='study_link_decisions')
    op.drop_table('study_link_decisions')
    op.drop_index(op.f('ix_studies_registration_id'), table_name='studies')
    op.drop_index(op.f('ix_studies_project_id'), table_name='studies')
    op.drop_table('studies')
    # ### end Alembic commands ###
