"""protocol and immutable screening

Revision ID: 85bd64d6c81a
Revises: c19a_discovery_slice
Create Date: 2026-09-20 17:44:08.387620

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from alembic import op

revision: str = '85bd64d6c81a'
down_revision: str | None = 'c19a_discovery_slice'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_protocols',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('research_plan_id', sa.Uuid(), nullable=False),
    sa.Column('framework_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('background', sa.Text(), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('research_question', sa.Text(), nullable=False),
    sa.Column('review_type', sa.String(length=50), nullable=False),
    sa.Column('screening_strategy', sa.Text(), nullable=False),
    sa.Column('extraction_strategy', sa.Text(), nullable=False),
    sa.Column('synthesis_strategy', sa.Text(), nullable=False),
    sa.Column('risk_of_bias_plan', sa.Text(), nullable=False),
    sa.Column('meta_analysis_plan', sa.Text(), nullable=False),
    sa.Column('meta_analysis_planned', sa.Boolean(), nullable=False),
    sa.Column('information_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('assumptions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('uncertainties', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by_agent_run_id', sa.Uuid(), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_agent_run_id'], ['agent_runs.id'], ),
    sa.ForeignKeyConstraint(['framework_id'], ['research_frameworks.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ),
    sa.ForeignKeyConstraint(['research_plan_id'], ['research_plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'version')
    )
    op.create_index(op.f('ix_review_protocols_project_id'), 'review_protocols', ['project_id'], unique=False)
    op.create_table('eligibility_criteria',
    sa.Column('protocol_id', sa.Uuid(), nullable=False),
    sa.Column('dimension', sa.String(length=50), nullable=False),
    sa.Column('operator', sa.String(length=20), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['protocol_id'], ['review_protocols.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eligibility_criteria_protocol_id'), 'eligibility_criteria', ['protocol_id'], unique=False)
    op.create_table('protocol_amendments',
    sa.Column('protocol_id', sa.Uuid(), nullable=False),
    sa.Column('from_version', sa.Integer(), nullable=False),
    sa.Column('to_version', sa.Integer(), nullable=False),
    sa.Column('field_path', sa.String(length=100), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('change_type', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['protocol_id'], ['review_protocols.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_protocol_amendments_protocol_id'), 'protocol_amendments', ['protocol_id'], unique=False)
    op.create_table('screening_decisions',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('work_id', sa.Uuid(), nullable=False),
    sa.Column('study_id', sa.Uuid(), nullable=True),
    sa.Column('protocol_id', sa.Uuid(), nullable=False),
    sa.Column('protocol_version', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Uuid(), nullable=False),
    sa.Column('stage', sa.String(length=30), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('reason_code', sa.String(length=50), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('reviewer_type', sa.String(length=10), nullable=False),
    sa.Column('reviewer_id', sa.Uuid(), nullable=True),
    sa.Column('agent_run_id', sa.Uuid(), nullable=True),
    sa.Column('criterion_assessments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence_spans', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ),
    sa.ForeignKeyConstraint(['protocol_id'], ['review_protocols.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['workflow_runs.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['work_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screening_decisions_project_id'), 'screening_decisions', ['project_id'], unique=False)
    op.create_index(op.f('ix_screening_decisions_protocol_id'), 'screening_decisions', ['protocol_id'], unique=False)
    op.create_index(op.f('ix_screening_decisions_round_id'), 'screening_decisions', ['round_id'], unique=False)
    op.create_index(op.f('ix_screening_decisions_work_id'), 'screening_decisions', ['work_id'], unique=False)
    op.execute("""
    CREATE FUNCTION protect_screening_history() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN RAISE EXCEPTION 'Scientific history is immutable'; END $$;
    CREATE TRIGGER screening_immutable BEFORE UPDATE OR DELETE ON screening_decisions
    FOR EACH ROW EXECUTE FUNCTION protect_screening_history();
    CREATE TRIGGER criteria_immutable BEFORE UPDATE OR DELETE ON eligibility_criteria
    FOR EACH ROW EXECUTE FUNCTION protect_screening_history();
    CREATE TRIGGER amendments_immutable BEFORE UPDATE OR DELETE ON protocol_amendments
    FOR EACH ROW EXECUTE FUNCTION protect_screening_history();
    CREATE FUNCTION protect_protocol_content() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      IF TG_OP = 'DELETE' THEN RAISE EXCEPTION 'Protocol versions are immutable'; END IF;
      IF (to_jsonb(NEW) - ARRAY['status','approved_at','approved_by']) IS DISTINCT FROM
         (to_jsonb(OLD) - ARRAY['status','approved_at','approved_by']) THEN
        RAISE EXCEPTION 'Create a new protocol version';
      END IF;
      RETURN NEW;
    END $$;
    CREATE TRIGGER protocol_versioned BEFORE UPDATE OR DELETE ON review_protocols
    FOR EACH ROW EXECUTE FUNCTION protect_protocol_content();
    CREATE UNIQUE INDEX screening_ai_once ON screening_decisions (protocol_id, work_id, stage)
    WHERE reviewer_type = 'AI';
    ALTER TABLE review_protocols ADD CHECK (status IN ('DRAFT','PROPOSED','APPROVED','SUPERSEDED','REJECTED'));
    ALTER TABLE screening_decisions ADD CHECK (stage IN ('TITLE_ABSTRACT','FULL_TEXT'));
    ALTER TABLE screening_decisions ADD CHECK (decision IN ('INCLUDE','EXCLUDE','UNCERTAIN','CONFLICT'));
    ALTER TABLE screening_decisions ADD CHECK (reviewer_type IN ('AI','HUMAN','SYSTEM'));
    ALTER TABLE screening_decisions ADD CHECK (confidence IS NULL OR confidence BETWEEN 0 AND 1);
    ALTER TABLE screening_decisions ADD CHECK (decision != 'EXCLUDE' OR reason_code IS NOT NULL);
    """)


def downgrade() -> None:
    op.execute("DROP TRIGGER protocol_versioned ON review_protocols")
    op.execute("DROP FUNCTION protect_protocol_content()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_screening_decisions_work_id'), table_name='screening_decisions')
    op.drop_index(op.f('ix_screening_decisions_round_id'), table_name='screening_decisions')
    op.drop_index(op.f('ix_screening_decisions_protocol_id'), table_name='screening_decisions')
    op.drop_index(op.f('ix_screening_decisions_project_id'), table_name='screening_decisions')
    op.drop_table('screening_decisions')
    op.drop_index(op.f('ix_protocol_amendments_protocol_id'), table_name='protocol_amendments')
    op.drop_table('protocol_amendments')
    op.drop_index(op.f('ix_eligibility_criteria_protocol_id'), table_name='eligibility_criteria')
    op.drop_table('eligibility_criteria')
    op.drop_index(op.f('ix_review_protocols_project_id'), table_name='review_protocols')
    op.drop_table('review_protocols')
    op.execute("DROP FUNCTION protect_screening_history()")
    # ### end Alembic commands ###
