"""evidence synthesis and manuscript

Revision ID: ad727dc1c78c
Revises: 926c9833b614
Create Date: 2026-09-20 22:16:42.341937

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from alembic import op

revision: str = "ad727dc1c78c"
down_revision: str | None = "926c9833b614"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "target_journals",
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("requirements", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "manuscript_plans",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("proposed_title", sa.String(length=500), nullable=False),
        sa.Column("article_type", sa.String(length=50), nullable=False),
        sa.Column("target_journal_id", sa.Uuid(), nullable=True),
        sa.Column("word_budget", sa.Integer(), nullable=False),
        sa.Column("created_by_agent_run_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_agent_run_id"], ["agent_runs.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["project_id"], ["research_projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_journal_id"], ["target_journals.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "version"),
    )
    op.create_index(
        op.f("ix_manuscript_plans_project_id"), "manuscript_plans", ["project_id"], unique=False
    )
    op.create_table(
        "manuscript_section_plans",
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column(
            "section_type",
            sa.Enum(
                "TITLE",
                "ABSTRACT",
                "KEYWORDS",
                "INTRODUCTION",
                "METHODS",
                "RESULTS",
                "DISCUSSION",
                "LIMITATIONS",
                "CONCLUSION",
                "REFERENCES",
                "APPENDIX",
                "CUSTOM",
                name="sectiontype",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("heading", sa.String(length=300), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("objectives", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("evidence_requirements", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("citation_requirements", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("target_words", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["plan_id"], ["manuscript_plans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_manuscript_section_plans_plan_id"),
        "manuscript_section_plans",
        ["plan_id"],
        unique=False,
    )
    op.create_table(
        "manuscripts",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "IN_REVIEW",
                "REVISION_REQUIRED",
                "NEEDS_AUTHOR_REVIEW",
                "READY_FOR_AUTHOR_REVIEW",
                "SUPERSEDED",
                name="manuscriptstatus",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("article_type", sa.String(length=50), nullable=False),
        sa.Column("target_journal_id", sa.Uuid(), nullable=True),
        sa.Column(
            "citation_style",
            sa.Enum("APA_7", "VANCOUVER", name="citationstyle", native_enum=False, length=40),
            nullable=False,
        ),
        sa.Column("authors", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("current_version_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["manuscript_plans.id"],
        ),
        sa.ForeignKeyConstraint(["project_id"], ["research_projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_journal_id"], ["target_journals.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_manuscripts_project_id"), "manuscripts", ["project_id"], unique=False)
    op.create_table(
        "manuscript_versions",
        sa.Column("manuscript_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "COMPLETE",
                "SUPERSEDED",
                name="manuscriptversionstatus",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("parent_version_id", sa.Uuid(), nullable=True),
        sa.Column("change_reason", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(length=20), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["manuscript_id"], ["manuscripts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["parent_version_id"], ["manuscript_versions.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("manuscript_id", "version"),
    )
    op.create_index(
        op.f("ix_manuscript_versions_manuscript_id"),
        "manuscript_versions",
        ["manuscript_id"],
        unique=False,
    )
    op.create_table(
        "evidence_syntheses",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("protocol_id", sa.Uuid(), nullable=True),
        sa.Column("research_question_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "GENERATED",
                "REVIEWED",
                "APPROVED",
                "SUPERSEDED",
                name="synthesisstatus",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column(
            "method",
            sa.Enum(
                "NARRATIVE_SYNTHESIS",
                "THEMATIC_SYNTHESIS",
                "DESCRIPTIVE_SYNTHESIS",
                name="synthesismethod",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("limitations", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("confidence_notes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_by_agent_run_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_agent_run_id"], ["agent_runs.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["project_id"], ["research_projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["protocol_id"], ["review_protocols.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["research_question_id"], ["research_questions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "research_question_id", "version"),
    )
    op.create_index(
        op.f("ix_evidence_syntheses_project_id"), "evidence_syntheses", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_evidence_syntheses_research_question_id"),
        "evidence_syntheses",
        ["research_question_id"],
        unique=False,
    )
    op.create_table(
        "manuscript_exports",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("manuscript_version_id", sa.Uuid(), nullable=False),
        sa.Column(
            "citation_style",
            sa.Enum("APA_7", "VANCOUVER", name="citationstyle", native_enum=False, length=40),
            nullable=False,
        ),
        sa.Column(
            "export_format",
            sa.Enum(
                "MARKDOWN",
                "DOCX",
                "PDF",
                "LATEX",
                name="exportformat",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "COMPLETED",
                "FAILED",
                name="exportstatus",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("exporter_version", sa.String(length=30), nullable=False),
        sa.Column("artifact_location", sa.String(length=1000), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["manuscript_version_id"], ["manuscript_versions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["project_id"], ["research_projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_manuscript_exports_manuscript_version_id"),
        "manuscript_exports",
        ["manuscript_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_manuscript_exports_project_id"), "manuscript_exports", ["project_id"], unique=False
    )
    op.create_table(
        "manuscript_sections",
        sa.Column("manuscript_version_id", sa.Uuid(), nullable=False),
        sa.Column("parent_section_id", sa.Uuid(), nullable=True),
        sa.Column("section_plan_id", sa.Uuid(), nullable=True),
        sa.Column(
            "section_type",
            sa.Enum(
                "TITLE",
                "ABSTRACT",
                "KEYWORDS",
                "INTRODUCTION",
                "METHODS",
                "RESULTS",
                "DISCUSSION",
                "LIMITATIONS",
                "CONCLUSION",
                "REFERENCES",
                "APPENDIX",
                "CUSTOM",
                name="sectiontype",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("heading", sa.String(length=300), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("word_count", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PLANNED",
                "WRITING",
                "DRAFT",
                "NEEDS_REVIEW",
                "COMPLETE",
                name="sectionstatus",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("created_by_agent_run_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_agent_run_id"], ["agent_runs.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["manuscript_version_id"], ["manuscript_versions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["parent_section_id"], ["manuscript_sections.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["section_plan_id"], ["manuscript_section_plans.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("manuscript_version_id", "position"),
    )
    op.create_index(
        op.f("ix_manuscript_sections_manuscript_version_id"),
        "manuscript_sections",
        ["manuscript_version_id"],
        unique=False,
    )
    op.create_table(
        "review_reports",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("manuscript_version_id", sa.Uuid(), nullable=False),
        sa.Column(
            "reviewer_type",
            sa.Enum(
                "SCIENTIFIC",
                "LITERATURE_COVERAGE",
                "CITATION_EVIDENCE",
                "METHODOLOGY",
                "WRITING",
                "JOURNAL",
                name="reviewertype",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("agent_run_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["agent_run_id"], ["agent_runs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["manuscript_version_id"], ["manuscript_versions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["project_id"], ["research_projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_review_reports_manuscript_version_id"),
        "review_reports",
        ["manuscript_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_review_reports_project_id"), "review_reports", ["project_id"], unique=False
    )
    op.create_table(
        "manuscript_citations",
        sa.Column("section_id", sa.Uuid(), nullable=False),
        sa.Column("work_id", sa.Uuid(), nullable=False),
        sa.Column("token", sa.String(length=80), nullable=False),
        sa.Column("start_offset", sa.Integer(), nullable=False),
        sa.Column("end_offset", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["section_id"], ["manuscript_sections.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["work_id"], ["work_records.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_manuscript_citations_section_id"),
        "manuscript_citations",
        ["section_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_manuscript_citations_work_id"), "manuscript_citations", ["work_id"], unique=False
    )
    op.create_table(
        "research_gaps",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("synthesis_id", sa.Uuid(), nullable=False),
        sa.Column(
            "gap_type",
            sa.Enum(
                "POPULATION_GAP",
                "METHOD_GAP",
                "OUTCOME_GAP",
                "GEOGRAPHIC_GAP",
                "LONGITUDINAL_GAP",
                "INCONSISTENT_EVIDENCE",
                "OTHER",
                name="gaptype",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("supporting_observation", sa.Text(), nullable=False),
        sa.Column("scope", sa.Text(), nullable=False),
        sa.Column(
            "confidence",
            sa.Enum(
                "INSUFFICIENT",
                "LOW",
                "MODERATE",
                "HIGH",
                name="confidencelevel",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["research_projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["synthesis_id"], ["evidence_syntheses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_research_gaps_project_id"), "research_gaps", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_research_gaps_synthesis_id"), "research_gaps", ["synthesis_id"], unique=False
    )
    op.create_table(
        "review_issues",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("manuscript_id", sa.Uuid(), nullable=False),
        sa.Column("manuscript_version_id", sa.Uuid(), nullable=False),
        sa.Column("section_id", sa.Uuid(), nullable=True),
        sa.Column(
            "reviewer_type",
            sa.Enum(
                "SCIENTIFIC",
                "LITERATURE_COVERAGE",
                "CITATION_EVIDENCE",
                "METHODOLOGY",
                "WRITING",
                "JOURNAL",
                name="reviewertype",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column(
            "severity",
            sa.Enum(
                "INFO",
                "MINOR",
                "MAJOR",
                "BLOCKING",
                name="reviewseverity",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("recommended_action", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "OPEN",
                "IN_PROGRESS",
                "RESOLVED",
                "DISMISSED",
                name="reviewissuestatus",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("resolution_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["manuscript_id"], ["manuscripts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["manuscript_version_id"], ["manuscript_versions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["project_id"], ["research_projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["section_id"], ["manuscript_sections.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_review_issues_manuscript_id"), "review_issues", ["manuscript_id"], unique=False
    )
    op.create_index(
        op.f("ix_review_issues_manuscript_version_id"),
        "review_issues",
        ["manuscript_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_review_issues_project_id"), "review_issues", ["project_id"], unique=False
    )
    op.create_table(
        "synthesis_contradictions",
        sa.Column("synthesis_id", sa.Uuid(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("interpretation", sa.Text(), nullable=True),
        sa.Column(
            "confidence",
            sa.Enum(
                "INSUFFICIENT",
                "LOW",
                "MODERATE",
                "HIGH",
                name="confidencelevel",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["synthesis_id"], ["evidence_syntheses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_synthesis_contradictions_synthesis_id"),
        "synthesis_contradictions",
        ["synthesis_id"],
        unique=False,
    )
    op.create_table(
        "synthesis_themes",
        sa.Column("synthesis_id", sa.Uuid(), nullable=False),
        sa.Column("label", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "confidence",
            sa.Enum(
                "INSUFFICIENT",
                "LOW",
                "MODERATE",
                "HIGH",
                name="confidencelevel",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["synthesis_id"], ["evidence_syntheses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_synthesis_themes_synthesis_id"), "synthesis_themes", ["synthesis_id"], unique=False
    )
    op.create_table(
        "revision_tasks",
        sa.Column("review_issue_id", sa.Uuid(), nullable=False),
        sa.Column("manuscript_id", sa.Uuid(), nullable=False),
        sa.Column("section_id", sa.Uuid(), nullable=True),
        sa.Column("action_type", sa.String(length=50), nullable=False),
        sa.Column("instruction", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "OPEN",
                "IN_PROGRESS",
                "COMPLETED",
                "CANCELLED",
                name="revisiontaskstatus",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("assigned_agent", sa.String(length=100), nullable=False),
        sa.Column("revision_round", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["manuscript_id"], ["manuscripts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["review_issue_id"], ["review_issues.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["section_id"], ["manuscript_sections.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_revision_tasks_manuscript_id"), "revision_tasks", ["manuscript_id"], unique=False
    )
    op.create_index(
        op.f("ix_revision_tasks_review_issue_id"),
        "revision_tasks",
        ["review_issue_id"],
        unique=False,
    )
    op.create_table(
        "synthesis_evidence_links",
        sa.Column("synthesis_id", sa.Uuid(), nullable=False),
        sa.Column("artifact_type", sa.String(length=30), nullable=False),
        sa.Column("artifact_id", sa.Uuid(), nullable=False),
        sa.Column("evidence_id", sa.Uuid(), nullable=False),
        sa.Column(
            "relationship",
            sa.Enum(
                "SUPPORTS",
                "CONTRADICTS",
                "QUALIFIES",
                "CONTEXTUALIZES",
                name="evidencerelationship",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["evidence_id"], ["evidence.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["synthesis_id"], ["evidence_syntheses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("artifact_type", "artifact_id", "evidence_id"),
    )
    op.create_index(
        op.f("ix_synthesis_evidence_links_artifact_id"),
        "synthesis_evidence_links",
        ["artifact_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_synthesis_evidence_links_evidence_id"),
        "synthesis_evidence_links",
        ["evidence_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_synthesis_evidence_links_synthesis_id"),
        "synthesis_evidence_links",
        ["synthesis_id"],
        unique=False,
    )
    op.create_table(
        "synthesis_findings",
        sa.Column("synthesis_id", sa.Uuid(), nullable=False),
        sa.Column("theme_id", sa.Uuid(), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column(
            "confidence",
            sa.Enum(
                "INSUFFICIENT",
                "LOW",
                "MODERATE",
                "HIGH",
                name="confidencelevel",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["synthesis_id"], ["evidence_syntheses.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["theme_id"], ["synthesis_themes.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_synthesis_findings_synthesis_id"),
        "synthesis_findings",
        ["synthesis_id"],
        unique=False,
    )
    op.create_table(
        "claims",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("source_finding_id", sa.Uuid(), nullable=True),
        sa.Column(
            "claim_type",
            sa.Enum(
                "BACKGROUND",
                "DESCRIPTIVE",
                "COMPARATIVE",
                "CAUSAL",
                "ASSOCIATIONAL",
                "METHOD",
                "SYNTHESIS",
                "LIMITATION",
                "INTERPRETATION",
                name="claimtype",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column(
            "basis",
            sa.Enum(
                "EVIDENCE",
                "PROJECT_ARTIFACT",
                "BACKGROUND",
                "INTERPRETATION",
                name="claimbasis",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "CANDIDATE",
                "VERIFIED",
                "REJECTED",
                "SUPERSEDED",
                name="claimstatus",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column(
            "confidence",
            sa.Enum(
                "INSUFFICIENT",
                "LOW",
                "MODERATE",
                "HIGH",
                name="confidencelevel",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=20), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("created_by_agent_run_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_agent_run_id"], ["agent_runs.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["research_projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["source_finding_id"], ["synthesis_findings.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_claims_project_id"), "claims", ["project_id"], unique=False)
    op.create_table(
        "claim_evidence_links",
        sa.Column("claim_id", sa.Uuid(), nullable=False),
        sa.Column("evidence_id", sa.Uuid(), nullable=False),
        sa.Column(
            "relationship",
            sa.Enum(
                "SUPPORTS",
                "CONTRADICTS",
                "QUALIFIES",
                "CONTEXTUALIZES",
                name="evidencerelationship",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column(
            "strength",
            sa.Enum(
                "INSUFFICIENT",
                "LOW",
                "MODERATE",
                "HIGH",
                name="confidencelevel",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["claim_id"], ["claims.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["evidence_id"], ["evidence.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("claim_id", "evidence_id", "relationship"),
    )
    op.create_index(
        op.f("ix_claim_evidence_links_claim_id"), "claim_evidence_links", ["claim_id"], unique=False
    )
    op.create_index(
        op.f("ix_claim_evidence_links_evidence_id"),
        "claim_evidence_links",
        ["evidence_id"],
        unique=False,
    )
    op.create_table(
        "claim_study_links",
        sa.Column("claim_id", sa.Uuid(), nullable=False),
        sa.Column("study_id", sa.Uuid(), nullable=False),
        sa.Column(
            "relationship",
            sa.Enum(
                "SUPPORTS",
                "CONTRADICTS",
                "QUALIFIES",
                "CONTEXTUALIZES",
                name="evidencerelationship",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["claim_id"], ["claims.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["study_id"], ["studies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("claim_id", "study_id", "relationship"),
    )
    op.create_index(
        op.f("ix_claim_study_links_claim_id"), "claim_study_links", ["claim_id"], unique=False
    )
    op.create_index(
        op.f("ix_claim_study_links_study_id"), "claim_study_links", ["study_id"], unique=False
    )
    op.create_table(
        "claim_verifications",
        sa.Column("claim_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "SUPPORTED",
                "PARTIALLY_SUPPORTED",
                "CONTRADICTED",
                "UNCERTAIN",
                "UNSUPPORTED",
                name="claimverificationstatus",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("recommended_qualification", sa.Text(), nullable=True),
        sa.Column(
            "confidence",
            sa.Enum(
                "INSUFFICIENT",
                "LOW",
                "MODERATE",
                "HIGH",
                name="confidencelevel",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("agent_run_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["agent_run_id"], ["agent_runs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["claim_id"], ["claims.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_claim_verifications_claim_id"), "claim_verifications", ["claim_id"], unique=False
    )
    op.create_table(
        "manuscript_claim_locations",
        sa.Column("section_id", sa.Uuid(), nullable=False),
        sa.Column("claim_id", sa.Uuid(), nullable=False),
        sa.Column("start_offset", sa.Integer(), nullable=False),
        sa.Column("end_offset", sa.Integer(), nullable=False),
        sa.Column("exact_text", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["claim_id"], ["claims.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["section_id"], ["manuscript_sections.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_manuscript_claim_locations_claim_id"),
        "manuscript_claim_locations",
        ["claim_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_manuscript_claim_locations_section_id"),
        "manuscript_claim_locations",
        ["section_id"],
        unique=False,
    )
    op.create_table(
        "section_plan_claims",
        sa.Column("section_plan_id", sa.Uuid(), nullable=False),
        sa.Column("claim_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["claim_id"], ["claims.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["section_plan_id"], ["manuscript_section_plans.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("section_plan_id", "claim_id"),
    )
    op.create_index(
        op.f("ix_section_plan_claims_claim_id"), "section_plan_claims", ["claim_id"], unique=False
    )
    op.create_index(
        op.f("ix_section_plan_claims_section_plan_id"),
        "section_plan_claims",
        ["section_plan_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_manuscripts_current_version",
        "manuscripts",
        "manuscript_versions",
        ["current_version_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.execute(
        """
        CREATE FUNCTION protect_complete_manuscript_section() RETURNS trigger AS $$
        BEGIN
            IF EXISTS (
                SELECT 1 FROM manuscript_versions
                WHERE id = OLD.manuscript_version_id AND status = 'COMPLETE'
            ) THEN
                RAISE EXCEPTION 'completed manuscript versions are immutable';
            END IF;
            RETURN COALESCE(NEW, OLD);
        END;
        $$ LANGUAGE plpgsql;
        CREATE TRIGGER immutable_complete_manuscript_sections
        BEFORE UPDATE OR DELETE ON manuscript_sections
        FOR EACH ROW EXECUTE FUNCTION protect_complete_manuscript_section();
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER immutable_complete_manuscript_sections ON manuscript_sections")
    op.execute("DROP FUNCTION protect_complete_manuscript_section")
    op.drop_constraint("fk_manuscripts_current_version", "manuscripts", type_="foreignkey")
    op.drop_index(op.f("ix_section_plan_claims_section_plan_id"), table_name="section_plan_claims")
    op.drop_index(op.f("ix_section_plan_claims_claim_id"), table_name="section_plan_claims")
    op.drop_table("section_plan_claims")
    op.drop_index(
        op.f("ix_manuscript_claim_locations_section_id"), table_name="manuscript_claim_locations"
    )
    op.drop_index(
        op.f("ix_manuscript_claim_locations_claim_id"), table_name="manuscript_claim_locations"
    )
    op.drop_table("manuscript_claim_locations")
    op.drop_index(op.f("ix_claim_verifications_claim_id"), table_name="claim_verifications")
    op.drop_table("claim_verifications")
    op.drop_index(op.f("ix_claim_study_links_study_id"), table_name="claim_study_links")
    op.drop_index(op.f("ix_claim_study_links_claim_id"), table_name="claim_study_links")
    op.drop_table("claim_study_links")
    op.drop_index(op.f("ix_claim_evidence_links_evidence_id"), table_name="claim_evidence_links")
    op.drop_index(op.f("ix_claim_evidence_links_claim_id"), table_name="claim_evidence_links")
    op.drop_table("claim_evidence_links")
    op.drop_index(op.f("ix_claims_project_id"), table_name="claims")
    op.drop_table("claims")
    op.drop_index(op.f("ix_synthesis_findings_synthesis_id"), table_name="synthesis_findings")
    op.drop_table("synthesis_findings")
    op.drop_index(
        op.f("ix_synthesis_evidence_links_synthesis_id"), table_name="synthesis_evidence_links"
    )
    op.drop_index(
        op.f("ix_synthesis_evidence_links_evidence_id"), table_name="synthesis_evidence_links"
    )
    op.drop_index(
        op.f("ix_synthesis_evidence_links_artifact_id"), table_name="synthesis_evidence_links"
    )
    op.drop_table("synthesis_evidence_links")
    op.drop_index(op.f("ix_revision_tasks_review_issue_id"), table_name="revision_tasks")
    op.drop_index(op.f("ix_revision_tasks_manuscript_id"), table_name="revision_tasks")
    op.drop_table("revision_tasks")
    op.drop_index(op.f("ix_synthesis_themes_synthesis_id"), table_name="synthesis_themes")
    op.drop_table("synthesis_themes")
    op.drop_index(
        op.f("ix_synthesis_contradictions_synthesis_id"), table_name="synthesis_contradictions"
    )
    op.drop_table("synthesis_contradictions")
    op.drop_index(op.f("ix_review_issues_project_id"), table_name="review_issues")
    op.drop_index(op.f("ix_review_issues_manuscript_version_id"), table_name="review_issues")
    op.drop_index(op.f("ix_review_issues_manuscript_id"), table_name="review_issues")
    op.drop_table("review_issues")
    op.drop_index(op.f("ix_research_gaps_synthesis_id"), table_name="research_gaps")
    op.drop_index(op.f("ix_research_gaps_project_id"), table_name="research_gaps")
    op.drop_table("research_gaps")
    op.drop_index(op.f("ix_manuscript_citations_work_id"), table_name="manuscript_citations")
    op.drop_index(op.f("ix_manuscript_citations_section_id"), table_name="manuscript_citations")
    op.drop_table("manuscript_citations")
    op.drop_index(op.f("ix_review_reports_project_id"), table_name="review_reports")
    op.drop_index(op.f("ix_review_reports_manuscript_version_id"), table_name="review_reports")
    op.drop_table("review_reports")
    op.drop_index(
        op.f("ix_manuscript_sections_manuscript_version_id"), table_name="manuscript_sections"
    )
    op.drop_table("manuscript_sections")
    op.drop_index(op.f("ix_manuscript_exports_project_id"), table_name="manuscript_exports")
    op.drop_index(
        op.f("ix_manuscript_exports_manuscript_version_id"), table_name="manuscript_exports"
    )
    op.drop_table("manuscript_exports")
    op.drop_index(
        op.f("ix_evidence_syntheses_research_question_id"), table_name="evidence_syntheses"
    )
    op.drop_index(op.f("ix_evidence_syntheses_project_id"), table_name="evidence_syntheses")
    op.drop_table("evidence_syntheses")
    op.drop_index(op.f("ix_manuscript_versions_manuscript_id"), table_name="manuscript_versions")
    op.drop_table("manuscript_versions")
    op.drop_index(op.f("ix_manuscripts_project_id"), table_name="manuscripts")
    op.drop_table("manuscripts")
    op.drop_index(
        op.f("ix_manuscript_section_plans_plan_id"), table_name="manuscript_section_plans"
    )
    op.drop_table("manuscript_section_plans")
    op.drop_index(op.f("ix_manuscript_plans_project_id"), table_name="manuscript_plans")
    op.drop_table("manuscript_plans")
    op.drop_table("target_journals")
    # ### end Alembic commands ###
