"""initial schema

Revision ID: b6ffd5d63bd9
Revises: 
Create Date: 2026-09-20 15:07:35.360268

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from alembic import op

revision: str = 'b6ffd5d63bd9'
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_definitions',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('input_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'DEPRECATED', name='agentdefinitionstatus', native_enum=False, length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version')
    )
    op.create_index(op.f('ix_agent_definitions_name'), 'agent_definitions', ['name'], unique=False)
    op.create_table('organizations',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('auth_provider', sa.String(length=50), nullable=False),
    sa.Column('provider_subject', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auth_provider', 'provider_subject')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_table('research_projects',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('working_title', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('research_method', sa.Enum('NARRATIVE_REVIEW', 'SCOPING_REVIEW', 'SYSTEMATIC_REVIEW', 'SYSTEMATIC_REVIEW_META_ANALYSIS', name='researchmethod', native_enum=False, length=40), nullable=True),
    sa.Column('status', sa.Enum('IDEA', 'EXPLORATION', 'PLANNING', 'PROTOCOL', 'SEARCHING', 'SCREENING', 'EXTRACTION', 'SYNTHESIS', 'ANALYSIS', 'WRITING', 'REVIEW', 'REVISION', 'AUTHOR_REVIEW', 'COMPLETED', 'ARCHIVED', name='projectstatus', native_enum=False, length=40), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('target_journal_id', sa.Uuid(), nullable=True),
    sa.Column('autonomy_mode', sa.Enum('GUIDED', 'BALANCED', 'AUTONOMOUS', name='autonomymode', native_enum=False, length=40), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_projects_organization_id'), 'research_projects', ['organization_id'], unique=False)
    op.create_index(op.f('ix_research_projects_status'), 'research_projects', ['status'], unique=False)
    op.create_table('agent_runs',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('agent_definition_id', sa.Uuid(), nullable=False),
    sa.Column('workflow_id', sa.String(length=300), nullable=True),
    sa.Column('task_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'SUCCESS', 'PARTIAL', 'NEEDS_HUMAN', 'NEEDS_MORE_EVIDENCE', 'INVALID_INPUT', 'FAILED', name='agentrunstatus', native_enum=False, length=40), nullable=False),
    sa.Column('model_provider', sa.String(length=50), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('input_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['agent_definition_id'], ['agent_definitions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_agent_definition_id'), 'agent_runs', ['agent_definition_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_project_id'), 'agent_runs', ['project_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_status'), 'agent_runs', ['status'], unique=False)
    op.create_index(op.f('ix_agent_runs_workflow_id'), 'agent_runs', ['workflow_id'], unique=False)
    op.create_table('duplicate_groups',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('duplicate_type', sa.Enum('EXACT_DOI', 'EXTERNAL_ID', 'EXACT_TITLE', 'FUZZY_TITLE', 'POTENTIAL_DUPLICATE', name='duplicategrouptype', native_enum=False, length=40), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'RESOLVED', name='duplicategroupstatus', native_enum=False, length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_duplicate_groups_project_id'), 'duplicate_groups', ['project_id'], unique=False)
    op.create_table('project_events',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('actor_type', sa.Enum('USER', 'AGENT', 'SYSTEM', name='projecteventactortype', native_enum=False, length=40), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_events_created_at'), 'project_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_project_events_event_type'), 'project_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_project_events_project_id'), 'project_events', ['project_id'], unique=False)
    op.create_table('project_members',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'EDITOR', 'REVIEWER', 'VIEWER', name='projectmemberrole', native_enum=False, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'user_id')
    )
    op.create_table('research_frameworks',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('framework_type', sa.Enum('PICO', 'PICOS', 'PCC', 'SPIDER', 'CUSTOM', name='researchframeworktype', native_enum=False, length=40), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('structured_elements', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_frameworks_project_id'), 'research_frameworks', ['project_id'], unique=False)
    op.create_table('research_ideas',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('conversation_message_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_ideas_project_id'), 'research_ideas', ['project_id'], unique=False)
    op.create_table('search_strategies',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('protocol_id', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'APPROVED', 'SUPERSEDED', name='searchartifactstatus', native_enum=False, length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_strategies_project_id'), 'search_strategies', ['project_id'], unique=False)
    op.create_table('usage_events',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('cost_estimate', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_events_created_at'), 'usage_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_usage_events_event_type'), 'usage_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_usage_events_organization_id'), 'usage_events', ['organization_id'], unique=False)
    op.create_table('work_records',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('doi', sa.String(length=300), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('publication_year', sa.Integer(), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('publication_type', sa.String(length=100), nullable=True),
    sa.Column('journal', sa.String(length=500), nullable=True),
    sa.Column('volume', sa.String(length=50), nullable=True),
    sa.Column('issue', sa.String(length=50), nullable=True),
    sa.Column('pages', sa.String(length=50), nullable=True),
    sa.Column('publisher', sa.String(length=300), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('open_access_status', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_records_doi'), 'work_records', ['doi'], unique=False)
    op.create_index(op.f('ix_work_records_project_id'), 'work_records', ['project_id'], unique=False)
    op.create_index(op.f('ix_work_records_publication_year'), 'work_records', ['publication_year'], unique=False)
    op.create_table('workflow_runs',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('temporal_workflow_id', sa.String(length=300), nullable=False),
    sa.Column('workflow_type', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='workflowrunstatus', native_enum=False, length=40), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_runs_project_id'), 'workflow_runs', ['project_id'], unique=False)
    op.create_index(op.f('ix_workflow_runs_status'), 'workflow_runs', ['status'], unique=False)
    op.create_index(op.f('ix_workflow_runs_temporal_workflow_id'), 'workflow_runs', ['temporal_workflow_id'], unique=True)
    op.create_table('duplicate_decisions',
    sa.Column('duplicate_group_id', sa.Uuid(), nullable=False),
    sa.Column('canonical_work_id', sa.Uuid(), nullable=True),
    sa.Column('decision', sa.Enum('MERGE', 'KEEP_SEPARATE', 'REVIEW_REQUIRED', name='duplicatedecisiontype', native_enum=False, length=40), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['canonical_work_id'], ['work_records.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['duplicate_group_id'], ['duplicate_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_duplicate_decisions_duplicate_group_id'), 'duplicate_decisions', ['duplicate_group_id'], unique=False)
    op.create_table('duplicate_members',
    sa.Column('duplicate_group_id', sa.Uuid(), nullable=False),
    sa.Column('work_id', sa.Uuid(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['duplicate_group_id'], ['duplicate_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_id'], ['work_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('duplicate_group_id', 'work_id')
    )
    op.create_index(op.f('ix_duplicate_members_duplicate_group_id'), 'duplicate_members', ['duplicate_group_id'], unique=False)
    op.create_index(op.f('ix_duplicate_members_work_id'), 'duplicate_members', ['work_id'], unique=False)
    op.create_table('research_plans',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PROPOSED', 'APPROVED', 'SUPERSEDED', 'REJECTED', name='researchplanstatus', native_enum=False, length=40), nullable=False),
    sa.Column('provisional_title', sa.String(length=500), nullable=True),
    sa.Column('problem_statement', sa.Text(), nullable=True),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('scope_summary', sa.Text(), nullable=True),
    sa.Column('recommended_method', sa.Enum('NARRATIVE_REVIEW', 'SCOPING_REVIEW', 'SYSTEMATIC_REVIEW', 'SYSTEMATIC_REVIEW_META_ANALYSIS', name='researchmethod', native_enum=False, length=40), nullable=True),
    sa.Column('recommended_framework', sa.Enum('PICO', 'PICOS', 'PCC', 'SPIDER', 'CUSTOM', name='researchframeworktype', native_enum=False, length=40), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('created_by_agent_run_id', sa.Uuid(), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_agent_run_id'], ['agent_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_plans_project_id'), 'research_plans', ['project_id'], unique=False)
    op.create_index('ix_research_plans_project_version', 'research_plans', ['project_id', 'version'], unique=False)
    op.create_table('search_queries',
    sa.Column('search_strategy_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'APPROVED', 'SUPERSEDED', name='searchartifactstatus', native_enum=False, length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['search_strategy_id'], ['search_strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_queries_provider'), 'search_queries', ['provider'], unique=False)
    op.create_index(op.f('ix_search_queries_search_strategy_id'), 'search_queries', ['search_strategy_id'], unique=False)
    op.create_table('work_identifiers',
    sa.Column('work_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('identifier_type', sa.Enum('DOI', 'OPENALEX_ID', 'SEMANTIC_SCHOLAR_ID', 'PMID', 'PMCID', 'ARXIV_ID', name='workidentifiertype', native_enum=False, length=40), nullable=False),
    sa.Column('identifier', sa.String(length=300), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['work_id'], ['work_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'identifier')
    )
    op.create_index(op.f('ix_work_identifiers_work_id'), 'work_identifiers', ['work_id'], unique=False)
    op.create_table('work_metadata_observations',
    sa.Column('work_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('field_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['work_id'], ['work_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_metadata_observations_provider'), 'work_metadata_observations', ['provider'], unique=False)
    op.create_index(op.f('ix_work_metadata_observations_work_id'), 'work_metadata_observations', ['work_id'], unique=False)
    op.create_table('work_verifications',
    sa.Column('work_id', sa.Uuid(), nullable=False),
    sa.Column('verification_type', sa.Enum('DOI_IDENTITY', 'METADATA_CONSISTENCY', 'URL_ACCESS', 'SOURCE_EXISTENCE', name='workverificationtype', native_enum=False, length=40), nullable=False),
    sa.Column('status', sa.Enum('VERIFIED', 'PARTIALLY_VERIFIED', 'UNVERIFIED', 'CONFLICT', 'FAILED', name='workverificationstatus', native_enum=False, length=40), nullable=False),
    sa.Column('verified_by', sa.String(length=200), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['work_id'], ['work_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_verifications_work_id'), 'work_verifications', ['work_id'], unique=False)
    op.create_table('research_questions',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('research_plan_id', sa.Uuid(), nullable=False),
    sa.Column('question_type', sa.String(length=50), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['research_plan_id'], ['research_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_questions_project_id'), 'research_questions', ['project_id'], unique=False)
    op.create_index(op.f('ix_research_questions_research_plan_id'), 'research_questions', ['research_plan_id'], unique=False)
    op.create_table('search_runs',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('search_query_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('executed_query', sa.Text(), nullable=False),
    sa.Column('executed_filters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result_count_reported', sa.Integer(), nullable=True),
    sa.Column('result_count_retrieved', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'PARTIAL', 'FAILED', 'CANCELLED', name='searchrunstatus', native_enum=False, length=40), nullable=False),
    sa.Column('provider_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('agent_run_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['search_query_id'], ['search_queries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_runs_project_id'), 'search_runs', ['project_id'], unique=False)
    op.create_index(op.f('ix_search_runs_provider'), 'search_runs', ['provider'], unique=False)
    op.create_index(op.f('ix_search_runs_search_query_id'), 'search_runs', ['search_query_id'], unique=False)
    op.create_index(op.f('ix_search_runs_status'), 'search_runs', ['status'], unique=False)
    op.create_table('search_results',
    sa.Column('search_run_id', sa.Uuid(), nullable=False),
    sa.Column('provider_record_id', sa.String(length=300), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('raw_payload_location', sa.String(length=500), nullable=True),
    sa.Column('normalized_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['search_run_id'], ['search_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('search_run_id', 'provider_record_id')
    )
    op.create_index(op.f('ix_search_results_search_run_id'), 'search_results', ['search_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_results_search_run_id'), table_name='search_results')
    op.drop_table('search_results')
    op.drop_index(op.f('ix_search_runs_status'), table_name='search_runs')
    op.drop_index(op.f('ix_search_runs_search_query_id'), table_name='search_runs')
    op.drop_index(op.f('ix_search_runs_provider'), table_name='search_runs')
    op.drop_index(op.f('ix_search_runs_project_id'), table_name='search_runs')
    op.drop_table('search_runs')
    op.drop_index(op.f('ix_research_questions_research_plan_id'), table_name='research_questions')
    op.drop_index(op.f('ix_research_questions_project_id'), table_name='research_questions')
    op.drop_table('research_questions')
    op.drop_index(op.f('ix_work_verifications_work_id'), table_name='work_verifications')
    op.drop_table('work_verifications')
    op.drop_index(op.f('ix_work_metadata_observations_work_id'), table_name='work_metadata_observations')
    op.drop_index(op.f('ix_work_metadata_observations_provider'), table_name='work_metadata_observations')
    op.drop_table('work_metadata_observations')
    op.drop_index(op.f('ix_work_identifiers_work_id'), table_name='work_identifiers')
    op.drop_table('work_identifiers')
    op.drop_index(op.f('ix_search_queries_search_strategy_id'), table_name='search_queries')
    op.drop_index(op.f('ix_search_queries_provider'), table_name='search_queries')
    op.drop_table('search_queries')
    op.drop_index('ix_research_plans_project_version', table_name='research_plans')
    op.drop_index(op.f('ix_research_plans_project_id'), table_name='research_plans')
    op.drop_table('research_plans')
    op.drop_index(op.f('ix_duplicate_members_work_id'), table_name='duplicate_members')
    op.drop_index(op.f('ix_duplicate_members_duplicate_group_id'), table_name='duplicate_members')
    op.drop_table('duplicate_members')
    op.drop_index(op.f('ix_duplicate_decisions_duplicate_group_id'), table_name='duplicate_decisions')
    op.drop_table('duplicate_decisions')
    op.drop_index(op.f('ix_workflow_runs_temporal_workflow_id'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_status'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_project_id'), table_name='workflow_runs')
    op.drop_table('workflow_runs')
    op.drop_index(op.f('ix_work_records_publication_year'), table_name='work_records')
    op.drop_index(op.f('ix_work_records_project_id'), table_name='work_records')
    op.drop_index(op.f('ix_work_records_doi'), table_name='work_records')
    op.drop_table('work_records')
    op.drop_index(op.f('ix_usage_events_organization_id'), table_name='usage_events')
    op.drop_index(op.f('ix_usage_events_event_type'), table_name='usage_events')
    op.drop_index(op.f('ix_usage_events_created_at'), table_name='usage_events')
    op.drop_table('usage_events')
    op.drop_index(op.f('ix_search_strategies_project_id'), table_name='search_strategies')
    op.drop_table('search_strategies')
    op.drop_index(op.f('ix_research_ideas_project_id'), table_name='research_ideas')
    op.drop_table('research_ideas')
    op.drop_index(op.f('ix_research_frameworks_project_id'), table_name='research_frameworks')
    op.drop_table('research_frameworks')
    op.drop_table('project_members')
    op.drop_index(op.f('ix_project_events_project_id'), table_name='project_events')
    op.drop_index(op.f('ix_project_events_event_type'), table_name='project_events')
    op.drop_index(op.f('ix_project_events_created_at'), table_name='project_events')
    op.drop_table('project_events')
    op.drop_index(op.f('ix_duplicate_groups_project_id'), table_name='duplicate_groups')
    op.drop_table('duplicate_groups')
    op.drop_index(op.f('ix_agent_runs_workflow_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_status'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_project_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_agent_definition_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_research_projects_status'), table_name='research_projects')
    op.drop_index(op.f('ix_research_projects_organization_id'), table_name='research_projects')
    op.drop_table('research_projects')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_agent_definitions_name'), table_name='agent_definitions')
    op.drop_table('agent_definitions')
    # ### end Alembic commands ###
