"""full_text_assets_and_parsed_documents

Revision ID: d34a95117685
Revises: 85bd64d6c81a
Create Date: 2026-09-20 20:07:55.586143

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from alembic import op

revision: str = 'd34a95117685'
down_revision: str | None = '85bd64d6c81a'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('full_text_acquisitions',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('work_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('NOT_REQUESTED', 'SEARCHING', 'AVAILABLE', 'ABSTRACT_ONLY', 'UNAVAILABLE', 'RETRIEVAL_FAILED', name='fulltextacquisitionstatus', native_enum=False, length=40), nullable=False),
    sa.Column('attempts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_id'], ['work_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'work_id')
    )
    op.create_index(op.f('ix_full_text_acquisitions_project_id'), 'full_text_acquisitions', ['project_id'], unique=False)
    op.create_index(op.f('ix_full_text_acquisitions_work_id'), 'full_text_acquisitions', ['work_id'], unique=False)
    op.create_table('full_text_assets',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('work_id', sa.Uuid(), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('source_type', sa.Enum('OPEN_ACCESS', 'USER_UPLOAD', 'LICENSED_SOURCE', 'OTHER', name='fulltextsourcetype', native_enum=False, length=40), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('byte_size', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'PARSING', 'PARSED', 'FAILED', 'REMOVED', name='fulltextassetstatus', native_enum=False, length=40), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=True),
    sa.Column('license_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['work_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_id', 'sha256')
    )
    op.create_index(op.f('ix_full_text_assets_project_id'), 'full_text_assets', ['project_id'], unique=False)
    op.create_index(op.f('ix_full_text_assets_sha256'), 'full_text_assets', ['sha256'], unique=False)
    op.create_index(op.f('ix_full_text_assets_work_id'), 'full_text_assets', ['work_id'], unique=False)
    op.create_table('parsed_documents',
    sa.Column('full_text_asset_id', sa.Uuid(), nullable=False),
    sa.Column('parser_name', sa.String(length=100), nullable=False),
    sa.Column('parser_version', sa.String(length=50), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('structure', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['full_text_asset_id'], ['full_text_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parsed_documents_full_text_asset_id'), 'parsed_documents', ['full_text_asset_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('parsed_document_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=False),
    sa.Column('page_end', sa.Integer(), nullable=False),
    sa.Column('section_path', sa.String(length=500), nullable=False),
    sa.Column('section_type', sa.String(length=30), nullable=False),
    sa.Column('heading_text', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=False),
    sa.Column('char_end', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['parsed_document_id'], ['parsed_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parsed_document_id', 'chunk_index')
    )
    op.create_index('document_chunk_section', 'document_chunks', ['parsed_document_id', 'section_type'], unique=False)
    op.create_index(op.f('ix_document_chunks_parsed_document_id'), 'document_chunks', ['parsed_document_id'], unique=False)
    # ### end Alembic commands ###
    op.execute("""
    CREATE FUNCTION protect_parse_result() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN RAISE EXCEPTION 'Parse results are immutable; re-parse creates a new document'; END $$;
    CREATE TRIGGER parsed_document_immutable BEFORE UPDATE OR DELETE ON parsed_documents
    FOR EACH ROW EXECUTE FUNCTION protect_parse_result();
    CREATE TRIGGER document_chunk_immutable BEFORE UPDATE OR DELETE ON document_chunks
    FOR EACH ROW EXECUTE FUNCTION protect_parse_result();
    ALTER TABLE full_text_assets ADD CHECK (byte_size > 0);
    ALTER TABLE full_text_assets ADD CHECK (char_length(sha256) = 64);
    ALTER TABLE parsed_documents ADD CHECK (page_count >= 0);
    ALTER TABLE parsed_documents ADD CHECK (status IN ('PARSED','PARTIAL','FAILED'));
    ALTER TABLE document_chunks ADD CHECK (page_start >= 1 AND page_end >= page_start);
    ALTER TABLE document_chunks ADD CHECK (char_start >= 0 AND char_end >= char_start);
    ALTER TABLE document_chunks ADD CHECK (token_count >= 0);
    """)


def downgrade() -> None:
    op.execute("DROP TRIGGER document_chunk_immutable ON document_chunks")
    op.execute("DROP TRIGGER parsed_document_immutable ON parsed_documents")
    op.execute("DROP FUNCTION protect_parse_result()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_chunks_parsed_document_id'), table_name='document_chunks')
    op.drop_index('document_chunk_section', table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_parsed_documents_full_text_asset_id'), table_name='parsed_documents')
    op.drop_table('parsed_documents')
    op.drop_index(op.f('ix_full_text_assets_work_id'), table_name='full_text_assets')
    op.drop_index(op.f('ix_full_text_assets_sha256'), table_name='full_text_assets')
    op.drop_index(op.f('ix_full_text_assets_project_id'), table_name='full_text_assets')
    op.drop_table('full_text_assets')
    op.drop_index(op.f('ix_full_text_acquisitions_work_id'), table_name='full_text_acquisitions')
    op.drop_index(op.f('ix_full_text_acquisitions_project_id'), table_name='full_text_acquisitions')
    op.drop_table('full_text_acquisitions')
    # ### end Alembic commands ###
